### ISSUE TITLE
Problem when I try to import a GTFS

### ISSUE THREAD

**Issue by HD24** [conveyal/gtfs-editor#138]
Hi,

Currently I have a problem when I'm trying to import a GTFS. This GTFS particularly has 5 routes, but each route has two directions. When I import this gtfs, it count all directions as a routes, and only import 5, when in this case there are 10. Anyone can help me?

Thanks!

**Comment by HD24** [comment]
I've been trying things and I've discovered that the number of routes is not important, when it makes five iterations(when it's adding trip pattern), the program stops...Somebody can help me?

Thanks.

**Comment by mattwigway** [comment]
I'm not sure I understand the issue; I can definitely import more than 5 routes locally. From your initial description it sounds like it should only import 5 routes, with the different directions as different trip patterns within each route.

**Comment by HD24** [comment]
I have problems when I'm trying to import a GTFS, during the process the uploader stops and I don't know why. If you want I can send you the GTFS.

**Comment by HD24** [comment]
Hi Matthew, can I send you the GTFS that I'm trying to import and it doesn't work? Thanks!

**Comment by mattwigway** [comment]
We're actually almost finished rewriting the GTFS importer and data storage layer, which I suspect will fix this.
		
		
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Fri, 27 Feb 2015 03:45:50 -0500  notifications@github.com  wrote ----Hi Matthew, can I send you the GTFS that I'm trying to import and it doesn't work? Thanks!

**Comment by HD24** [comment]
I will wait this update, thanks!

**Comment by mattwigway** [comment]
I think this should be fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with). Feel free to reopen if it isn't.
