### ISSUE TITLE
'Calculate Times' for trip patterns produces inconsistent results

### ISSUE THREAD

**Issue by markjd84** [conveyal/gtfs-editor#154]
On the trip pattern editor - Step 3 of the workflow - the timing calculator button seems to produce slightly unpredictable results – two stops at distances of very similar length have quite different times, and stops at longer distances do not seem to have proportionate times. 
 
It looks like the `calcTripPatternTimes` method is using the geometry to the previous stop and the geometry to the current stop as one might expect, but I wonder if there is something in the [distance calculation](https://github.com/conveyal/gtfs-editor/blob/0.1.3/app/controllers/Api.java#L595) when the trip pattern is created that is going wrong somehow? Just a guess – sorry I can’t be more help.  

![calc times](https://cloud.githubusercontent.com/assets/6650143/6129319/8061bd98-b135-11e4-8865-c082d6e5344e.png)

**Comment by markjd84** [comment]
I should have said, I am happy to work on this (in fact we will need it fairly soon) unless there is something already in the pipeline! Thanks.

**Comment by mattwigway** [comment]
Hi, haven't seen this before. If you'd like to take a stab at it go for it! Let me know if I can be of assistance.

Also, currently we're depending on the fix-gtfs-loader branch of OTP, which isn't available in binary form, so you have to build it and drop the jar into lib/. I'll try to rectify that today.

**Comment by mattwigway** [comment]
OK, above comment no longer applies, no need to build OTP manually. Just run `play dependencies` and you should be good to go.

**Comment by dgoujard** [comment]
I have similar issue when i duplicate trip pattern, reverse stop sequence and use timing tool.
I got negative time, i think it's related to the trip shape, it may be need to reverse the geojson coordinates.

![capture d ecran 2015-02-17 a 11 20 12](https://cloud.githubusercontent.com/assets/51832/6226638/6dd211ca-b697-11e4-8ac5-a0719406e907.png)

i will try to inversate trip path

**Comment by markjd84** [comment]
I'm confused,  does this fix the timing calculation in *both directions* or just on the reversed pattern? Mine was producing inconsistent times in both directions, but looking at your PR I think only what gets drawn when reversing is being changed. It might therefore be that there are **two** bugs here.

If not though, great - saves me a job!

**Comment by dgoujard** [comment]
My fix is for the reverse pattern only (switch get method to set in the code). Maybe i would need to create another ticket for this.

**Comment by dgoujard** [comment]
I'm using the current master branch and tried to reproduce your bug but i think it's resolved with current master.
See :
![capture d ecran 2015-02-17 a 14 17 46](https://cloud.githubusercontent.com/assets/51832/6228739/e677aae6-b6af-11e4-8523-733f38bb2f6d.png)

Maybe i'm wrong but it's seems like linear?

**Comment by markjd84** [comment]
Thanks, I will install and check it over!
