### ISSUE TITLE
'Export as GTFS' produces very little data

### ISSUE THREAD

**Issue by markjd84** [conveyal/gtfs-editor#168]
We have a database set up with around 120 routes, each with quite complicated (and carefully digitised!) trip patterns. However when we come to export these routes, only one shows up in the resulting GTFS zip file. Can not find anything particularly special about that one in terms of settings - all the routes are marked as Pending + Publicly Visible. 

Strangely, the GIS export works fine. Using export dates from today to one year from today. Any advice much appreciated!

**Comment by mattwigway** [comment]
Hmm. Which commit of the editor are you using? We recently rewrote the entire export logic from scratch.

**Comment by markjd84** [comment]
I've got 0.1.3 as installed before Christmas. Shall I upgrade to 0.2 and try that? Cheers.

**Comment by mattwigway** [comment]
Yeah, give that a shot. I'm hoping this was an export problem rather than a data model problem, as the latter are harder to fix.

**Comment by markjd84** [comment]
Still having problems with v2 I'm afraid (see #176) but in order to try and get the data exported from our v1 installation, have copied across the whole database from our v1 to v2 machine. Then running the export gives 

```
Execution exception (In /app/jobs/ProcessGtfsSnapshotExport.java around line 94)
OutOfMemoryError occured : Java heap space
```

**Comment by dgoujard** [comment]
@markjd84 have you try to use my vm in the #174 ticket ? I think it would export, just import your postgresql database.

**Comment by markjd84** [comment]
Brilliant @dgoujard  - massive thanks for the VM. 

I'm afraid however I'm still getting the message below when trying to export our routes, even using your machine and following the dependency instructions in #171. It is a *lot* of routes (around 120, each with ~60 stops) - but I'm not convinced that would be enough to cause this.

```
Execution exception (In /app/jobs/ProcessGtfsSnapshotExport.java around line 94)
OutOfMemoryError occured : Java heap space
```

Does your export work? If so - is it a lot of routes or a small number? 

Can I be really cheeky and ask if you did anything different in setup of this VM outside the instructions in `INSTALL.md` ?

**Comment by dgoujard** [comment]
Hi,

I just follow install.md and complete the instruction with additional download of jar.

My export work, but i didn't have many routes (it's just test setup).

It's maybe not enough RAM for the export (it would be strange). Have you check with top ou htop the memory usage when you request export?

**Comment by markjd84** [comment]
Right... it works if I give the VM and Play far more RAM (stuck it up to 1.5G). 

However, we still only get one route output from the export!

**Comment by markjd84** [comment]
Upon closer inspection, it appears there are no actual trips ever being generated in the database. We have routes, and trip patterns, but for some reason the table `trip` is almost empty. I wonder if it's something to do with using frequency-based trips?

**Comment by mattwigway** [comment]
Yep, that's expected behavior. If the pattern runs from 8am to 10pm every 5 minutes, that's represented as a single trip. It should, however, produce frequencies.txt entries from them. That doesn't explain why you're only seeing a single route, however.

**Comment by mattwigway** [comment]
I think this should be fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with).
