### ISSUE TITLE
Timing generation generate errors

### ISSUE THREAD

**Issue by dgoujard** [conveyal/gtfs-editor#170]
Hi,

When i'm editing an trip pattern, and set 50 in "km/h" input and 10 or 00:10 in "Dwell time" i got an error in the console : 
```
@6l7pmifp8
Internal Server Error (500) for request GET /api/calctrippatterntimes?id=8&velocity=13.888900000000001&defaultDwell=0

Execution exception (In /app/controllers/Api.java around line 645)
NullPointerException occured : null

play.exceptions.JavaExecutionException
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException
	at controllers.Api.calcTripPatternTimes(Api.java:645)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
```

**Comment by mattwigway** [comment]
Is this data that's been imported from GTFS feed, or data you've created? If the former, this is a known issue #156, which should be fixed very soon (you would have to reimport your data). Otherwise, something else is going on.

**Comment by dgoujard** [comment]
Hi, thanks for your answer, i'm not importing existing GTFS data. I use the current master branch

**Comment by dgoujard** [comment]
Resolved, it's caused by wrong install (dependencies). 
My install working install process is 
* Remove all jar in lib folder
* run play dependencies
* Download deleted jar from step 1
* Download this missings jar 
wget http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
wget http://dev.mapfish.org/maven/repository/voldemort/store/compress/h2-lzf/1.0/h2-lzf-1.0.jar
wget http://download.osgeo.org/webdav/geotools/java3d/vecmath/1.3.2/vecmath-1.3.2.jar
* Start the project with play run

**Comment by mattwigway** [comment]
Thanks for tracking this down. clearly there are some dependency issues that need to be addressed.
