### ISSUE TITLE
Pickup/Dropoff type not exporting

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-editor#190]
@mattwigway In the previous version of the editor, a user could indicate [pickup/dropoff type](https://developers.google.com/transit/gtfs/reference#stop_times_fields) for a given stop_time with the following notation system in the schedule spreadsheets:

![image](https://cloud.githubusercontent.com/assets/2370911/6463629/036223ca-c182-11e4-9baa-54f496301a11.png)

However, some bug prevented these fields from accompanying the GTFS export.  It looks like the new version wipes any character that's not a lone dash or HH:MM:SS.  Do you plan to add support for these fields?

**Comment by mattwigway** [comment]
You can specify them per stop in the stop edit view. There's currently no way in the UI to specify them per stop time, although the code is there on the backend (patches accepted!)
		
		
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Tue, 03 Mar 2015 08:51:40 -0500  notifications@github.com  wrote ----@mattwigway In the previous version of the editor, a user could indicate pickup/dropoff type for a given stop_time with the following notation system in the schedule spreadsheets:

However, some bug prevented these fields from accompanying the GTFS export.  It looks like the new version wipes any character that's not a lone dash or HH:MM:SS.  Do you plan to add support for these fields?

**Comment by landonreed** [comment]
Thanks, I'll look into this!

**Comment by landonreed** [comment]
OK, I just checked out the stop edit view and my changes won't save.  Do you experience the same behavior?

**Comment by mattwigway** [comment]
Sure enough, thanks for the report. Fixed.
