### ISSUE TITLE
Memory leak, during line creation?

### ISSUE THREAD

**Issue by medwards** [conveyal/gtfs-editor#191]
While adding some pretend stops for the U6 in Berlin I get 8 transaction errors:  
`16:23:19,207 ERROR ~ DB transaction left unclosed, this signifies a memory leak!`

I added 7 stops so thats why I think the transaction is left open in a previous step. This is a brand new instance so all I did was add a transit type and the initial data for the line.

Then I created an alignment and it spammed the log with this message...

Doesn't seem like it has an impact at the moment, just raising the issue.

**Comment by mattwigway** [comment]
Yep, this is something I need to look into. This message is from the finalizer, so the memory is being freed, but it should be freed before that.

**Comment by mattwigway** [comment]
It means that a transaction is left open and is being closed by the finalizer.

**Comment by mattwigway** [comment]
Ok, here's the issue. Evidently when you call one of the render() methods in Play 1.2, it interrupts the flow of the calling function so any additional code is not executed, _including any finally { } blocks_ .

This is undesirable. For the time being letting the finalizer close things works, although it's far from ideal. We could invest energy into fixing this or wait until we switch to play 2 (#165) which follows the typical flow of the java language.
