### ISSUE TITLE
Cannot run GTFS-Editor after 'git pull' 

### ISSUE THREAD

**Issue by JWJoubert** [conveyal/gtfs-editor#212]
After encountering issue [#210](https://github.com/conveyal/gtfs-editor/issues/210) I thought it might be time for an update... and reading a few things about `mapdb` being implemented in February, I thought: "right, it IS time for an upgrade".

So I did.

Now I cannot even get GTFS-Editor running, I get a `ExceptionInInitializerError occured : null` error, with a reference to

    In /app/controllers/Application.java (around line 43)

    39: 	
    40:  @Before
    41:    static void initSession() throws Throwable {
    42: 
    43:        GlobalTx tx = VersionedDataStore.getGlobalTx();

On refreshing/reloading the page, the error changes to `NoClassDefFoundError occured : Could not initialize class datastore.VersionedDataStore`

I try to look into the the `VersionedDataStore` but I'm a bit lost, other than realising that `GlobalTx` is a `mapdb`-related object. Still, I think a major problem is the fact that the original GTFS feed was created in `Postgresql` , and I guess `mapdb` does not play very nicely. This might also be why issue [#210](https://github.com/conveyal/gtfs-editor/issues/210) does not want to save alignment edits?

Is there a way to fix it, i.e. just get GTFS-Editor running again? I have a copy of the GTFS feed which I can import (but only if I get the editor running of course).

**Comment by markjd84** [comment]
What do you have in your `application.conf` ? I have been changing line 114 to `db=fs` (and uncommenting) which lets it use a file as a database, as I understand it.

**Comment by JWJoubert** [comment]
Thanks Mark.
Mine was commented out as well. I added `db=fs`, restarted the editor, but same error.

**Comment by JWJoubert** [comment]
Tried commenting the `postgres` three lines out, same error.

**Comment by JWJoubert** [comment]
I've been able to get a local version running by simply overwriting the `application.conf` file with the `application.conf.template` ... but it does not import the GTFS feed that was exported using the `postgresql` version of the editor I used.

Is there a way to fetch a _working_ GIT sha-1 commit? Or rather, to _which_ SHA-1 should I revert to get my old version back?

**Comment by JWJoubert** [comment]
I had to start from scratch and re-installed gtfs-editor completely... so I guess I can close this issue. Maybe I just messed up the transition to the new database type. If someone stumbles across this issue again, they can consider re-opening it.
