### ISSUE TITLE
Feature Request: edit & manage fares

### ISSUE THREAD

**Issue by dcunited001** [conveyal/gtfs-editor#233]
I just noticed that the app doesn't manage fares.  This seems fairly straightforward.  I just forked the app to deploy on Heroku, so i might end up adding this to my fork anyways.  

Is this a feature you want in the app?  How should I go about adding something like this?

**Comment by licarth** [comment]
Hey, any update around fare support ? 

@dcunited001 Did you implement this as part of your fork ?

Related to #56.
