### ISSUE TITLE
Feature Request: enable input of simple formulas in schedule editor

### ISSUE THREAD

**Issue by estolze** [conveyal/gtfs-editor#234]
If a dataset contains numerous stops, but only the departure time at the initial stop is given (the travelling time between one stop to the next is constant between one trip and another), it would be great if one could edit times for each stop as a simple formula:

**Comment by mattwigway** [comment]
In the trip pattern editor you can set a default dwell and travel time. Then if you fill in one time you can drag the lower-right corner of the cell to the right to autofill the remaining times based on the pattern. You can also select a trip and use the o key to offset the times or the i key to insert a new trip based on the selected trip, but offset in time.

**Comment by estolze** [comment]
Thanks a lot for the hint, this is what I was looking for!
