### ISSUE TITLE
deploy to dotcloud

### ISSUE THREAD

**Issue by dcunited001** [conveyal/gtfs-editor#237]
Hey, i'm working on deploying the GTFS editor to dotcloud.  I'm doing this as volunteer work for a local transit agency.  In your [deploy docs](https://github.com/conveyal/gtfs-editor/blob/master/doc/deploy.md), i noticed that it says that this product can be deployed with the 'old CLI'.  

I'm trying to deploy using the new CLI.  Is there any way to do this?  The Dotcloud references using Heroku buildpacks for custom deploys.  Should I set up a custom buildpack?

When I try to push, this is what I'm getting:

```
Counting objects: 4908, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (1806/1806), done.
Writing objects: 100% (4908/4908), 83.58 MiB | 1.34 MiB/s, done.
Total 4908 (delta 3057), reused 4908 (delta 3057)

-----> Receiving push
 !     cloudControl push rejected, failed to determine buildpack for java app
 !
remote: error: hook declined to update refs/heads/master
To ssh://roanokegtfs@dotcloudapp.com/repository.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'ssh://roanokegtfs@dotcloudapp.com/repository.git'
Command '['/usr/bin/git', 'push', u'ssh://roanokegtfs@dotcloudapp.com/repository.git', 'master']' returned non-zero exit status 1
```

when i run `dotcloud roanokegtfs log deploy` or any of the other logs, i don't see any information about why it's failing.

**Comment by dcunited001** [comment]
i was able to get past this by using a custom buildpack.  dotcloud is compatible with heroku buildpacks, so i used the [play buildpack](https://github.com/heroku/heroku-buildpack-play).  

However, i needed to specify the version of java and play with a few extra commits.  I've got this to run on Heroku with this configuration.  On Dotcloud, it's now deploying, but I'm getting a 503, but there are no application logs unfortunately.  Again, I'm trying to use the `dotcloud APP_NAME log {access,error,worker,deploy}` command, but i'm not getting any information.

**Comment by dcunited001** [comment]
Are you guys still supporting this software?

**Comment by mattwigway** [comment]
We do still provide hosted GTFS Editing and some support for bugfixes; however, we haven't deployed to dotcloud in many years as it's no longer part of our stack.
