### ISSUE TITLE
Compilation error with new install

### ISSUE THREAD

**Issue by bbobrian** [conveyal/gtfs-editor#255]
Compilation error
The file /app/controllers/api/CalendarController.java could not be compiled. Error raised is : The method apply(String) of type new Function<String,ServiceCalendar.ServiceCalendarForPattern>(){} must override a superclass method

I'm guessing I may be trying to use an incompatible version of something.

OS: Windows 7
Java: 1.8.0_91
Groovy: 2.4.6
Play Framework: 1.2.5.6

**Comment by j05u3** [comment]
I think you need java 7

**Comment by bbobrian** [comment]
So much for Java's claimed backward compatibility. Switched to 1.7.0_79 and it seems to be working.

**Comment by cascafico** [comment]
I just installed java 8 to have OpenTripPlanner working... and now gtfs-editor is not working anymore.
I got back 7 with sudo update-alternatives --config java
Does somebody know how to switch via environment variables?
