### ISSUE TITLE
Where can I find the database definition?

### ISSUE THREAD

**Issue by mdepablo** [conveyal/gtfs-editor#66]
Hi,

I'm trying to run this project but I can't make it work. I have the application running but I can't pass the login screen because I don't have the database model. Can you guide me of where can I found the sql or anything else where is defined the database model?

I'm running it on my Windows and have configured a MySQL server for it.

Thanks

**Comment by mattwigway** [comment]
We no longer use a relational database, so starting the app should now be sufficient.
