### ISSUE TITLE
Client leaflet.js errors prevent use of application

### ISSUE THREAD

**Issue by alaw005** [conveyal/gtfs-editor#86]
I am getting a number of errors with leaflet.js when trying on the route stops page (e.g. http://192.168.15.96:9000/route/64726/stops) that prevent me from moving around the map, zooming in or adding any points. The following shows the javascript errors I am getting in Chrome:

```javascript
2Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (min-resolution: 144dpi) stops:1
Uncaught TypeError: Cannot read property '_leaflet_click36' of undefined 192.168.15.96:9000/public/javascripts/lib/leaflet.js:8
Uncaught TypeError: Cannot set property '_leaflet_pos' of null leaflet.js:6
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. leaflet.js:7
Uncaught TypeError: Cannot set property '_leaflet_pos' of null leaflet.js:6
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. leaflet.js:7
Uncaught TypeError: Cannot set property '_leaflet_pos' of null leaflet.js:6
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. leaflet.js:7
GET http://192.168.15.96:9000/public/javascripts/lib/backbone-min.map 404 (Not Found) :9000/public/javascripts/lib/backbone-min.map:1
2Uncaught TypeError: undefined is not a function
```

Probably not related, but when I start the application, which I am running in a Vagrant/Docker machine, I get the error "No configuration file hibernate-spatial.cfg.xml on the classpath".

**Comment by mattwigway** [comment]
This issue doesn't seem to be live, so I'm closing it. Reopen with more info if need be.

**Comment by markjd84** [comment]
Just to add a +1 to this, I was experiencing exactly the same issues as described, was on release 0.3.9.

However swapping out Leaflet and Leaflet.label to 0.7.3 and 0.2.1 respectively in `public/javascripts/lib` seems to have fixed it. Thought worth recording in case anyone else comes across this weird one.
