### ISSUE TITLE
Upload and export other file types

### ISSUE THREAD

**Issue by ianstott** [conveyal/gtfs-editor#9]
Want to be able to upload and export data from different sources (such as .SHP / .KML).

o	Include support for data upload and export.
o	Note that KML can be tricky to import, since it often requires cleaning.
o	Open question whether an automated KML import tool is relevant (i.e. will it be used repeatedly), or whether it is a one-off effort every time.
o	DGT / CTS EMBARQ has about 10% of all routes encoded in KML data (requested for them to share).
o	Metrobus has additional KML data which will ideally need to be imported.

**Comment by mattwigway** [comment]
The trouble is that shapefiles don't have a well-defined schema, so it kind of does have to be a one-off.
